"""
Django settings for kalimunda project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.

# BASE_DIR = Path(__file__).resolve().parent.parent   # wea re leaving it for jungle to look for the file but wont resolve to path of yo project

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # wea re leaving it for jungle to look for the file but wont resolve to path of yo project
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(rzfhs6^$1%46w3r&t2cbty4mrzpc!p0v_x#ith8dts#p+z#np'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # predefined django Apps installed here
    'django.contrib.admin', # app admins details
    'django.contrib.auth', # authentication
    'django.contrib.contenttypes',
    'django.contrib.sessions', # sessions of users helps keep track of users logins and logouts
    'django.contrib.messages', # messages
    'django.contrib.staticfiles', # for images, CSS
    'crispy_forms',
    'crispy_bootstrap4',
    'dawa', # my new created App of project called Dawa
    
    # 'django_filters',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kalimunda.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [], #specifying the path for your directory files of templates
        'DIRS': [os.path.join(BASE_DIR, "templates")], #specifying the path for your directory files of templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kalimunda.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR/ 'db.sqlite3', # in project folder templates find db.sqlite3
        'NAME': os.path.join( BASE_DIR, 'db.sqlite3'), # in project folder templates find db.sqlite3
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# defining 
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuring crispy forms package with bootstrap4 version for better forms & UI
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Our sucessful login url route redirect the user to home template
LOGIN_REDIRECT_URL = 'home'

# Setting login URL redirect for users to login into the app
LOGIN_URL = 'login'