# Generated by Django 4.1.7 on 2023-03-23 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dawa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(blank=True, max_length=50, null=True)),
                ('totalQuantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issuedQuantity', models.IntegerField(blank=True, default=0, null=True)),
                ('recievedQuantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unitPrice', models.IntegerField(blank=True, default=0, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('categoryName', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dawa.category')),
            ],
        ),
    ]
